# Generated by Django 4.0.4 on 2022-05-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_alter_glasses_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='json_data',
            field=models.TextField(default='{}', verbose_name='JSON data'),
        ),
    ]
